austen = Author.create(name: "Jane Austen")
pratchett = Author.create(name: "Terry Pratchett")
gaiman = Author.create(name: "Neil Gaiman")
kingsolver = Author.create(name: "Barbara Kingsolver")
liu = Author.create(name: "Cixin Liu")
herbert = Author.create(name: "Frank Herbert")
harkaway = Author.create(name: "Nick Harkaway")
novik = Author.create(name: "Naomi Novik")
murakami = Author.create(name: "Haruki Murakami")
hannah = Author.create(name: "Kristin Hannah")
tartt = Author.create(name: "Donna Tartt")

pride_and_prejudice = Book.create!(title: "Pride and Prejudice", publication_year: 1813, pages: 432, authors: [austen], cover_art: "https://images-na.ssl-images-amazon.com/images/I/51sOyMmEYBL._SX310_BO1,204,203,200_.jpg")
good_omens = Book.create!(title: "Good Omens", publication_year: 1990, pages: 288, authors: [pratchett, gaiman], cover_art: "https://images-na.ssl-images-amazon.com/images/I/81Ig%2Br7RTKL.jpg")
sense_and_sensibility = Book.create!(title: "Sense and Sensibility", publication_year: 1811, pages: 352, authors: [austen], cover_art: "https://images.gr-assets.com/books/1176166955l/600331.jpg")
poisonwood_bible = Book.create!(title: "The Poisonwood Bible", publication_year: 1998, pages: 546, authors: [kingsolver], cover_art: "https://i.pinimg.com/236x/85/8f/8e/858f8e3a58b6cde30f804495a7a70b0f--barbara-kingsolver-bible.jpg")
three_body = Book.create!(title: "The Three-Body Problem", publication_year: 2014, pages: 400, authors: [liu], cover_art: "https://images.gr-assets.com/books/1415428227l/20518872.jpg")
dune = Book.create!(title: "Dune", publication_year: 1999, pages: 517, authors: [herbert], cover_art: "https://images.gr-assets.com/books/1395160437l/53747.jpg")
gone_away = Book.create!(title: "The Gone-Away World", publication_year: 531, pages: 544, authors: [harkaway], cover_art: "https://images.gr-assets.com/books/1328322676l/3007704.jpg" )
uprooted = Book.create!(title: "Uprooted", publication_year: 2015, pages: 448, authors: [novik], cover_art: "http://t3.gstatic.com/images?q=tbn:ANd9GcQlUX2MfH_OzRAjN9VOF-Ftb-7Jge7kFxHt0ou0pAOiGzimph6h")
spinning_silver = Book.create!(title: "Spinning Silver", publication_year: 2018, pages: 480, authors: [novik], cover_art: "http://t0.gstatic.com/images?q=tbn:ANd9GcRrXzs8bmTSq0LoJBO6nLkQK5A0W6Bay0LZ3kkjRK4zidHoyR73")
graveyard_book = Book.create!(title: "The Graveyard Book", publication_year: 2008, pages: 312, authors: [gaiman], cover_art: "https://upload.wikimedia.org/wikipedia/en/3/3e/TheGraveyardBook_Hardcover.jpg")
iq84= Book.create!(title: "1Q84", publication_year: 2011, pages: 1184, authors: [murakami], cover_art: "https://booklife.com/image-factory/http/localhost/amazongetcover/9780307593313.jpg/w204.jpg")
nightingale= Book.create!(title: "The Nightingale", publication_year: 2015, pages: 440, authors: [hannah], cover_art: "http://t1.gstatic.com/images?q=tbn:ANd9GcShNR3u-bHpxG48-M8415L_BR9ABzRIJt7my0BBJGHI6XivaACu")
goldfinch = Book.create!(title: "The Goldfinch", publication_year: 2013, pages: 784, authors: [tartt], cover_art: "https://www.littlebrown.com/wp-content/uploads/2017/06/9780316055437.jpg?fit=439%2C675")

sense_and_sensibility.reviews.create!(title: "Austen is the best", rating: 4, user: "rene", description: "It's not quite P&P, but it's probably my second-favorite Jane Austen book.")
sense_and_sensibility.reviews.create!(title: "Girl books are so boring", rating: 1, user: "smitty", description: "Really long and dull.")
dune.reviews.create!(title: "Classic and awesome", rating: 5, user: "rene", description: "Has so many now-familiar sci-fi tropes. Such a great book!")
pride_and_prejudice.reviews.create!(title: "A perfect book", rating: 5, user: "rene", description: "Beautiful. Charming. Wonderful.")
poisonwood_bible.reviews.create!(title: "Incredible", rating: 5, user: "rene", description: "Definitely one of my top 5 of all time. So moving.")
poisonwood_bible.reviews.create!(title: "Didn't really like it", rating: 2, user: "smitty", description: "I thought there would be more bible stories")
uprooted.reviews.create!(title: "One of my all-time faves", rating: 5, user: "rene", description: "One of the few books I finished and then immediately re-read again. Love this book.")
spinning_silver.reviews.create(title: "Amazing follow-up to Uprooted", rating: 5, user: "rene", description: "I was nervous this one wouldn't be as good as Uprooted, but it is!")
graveyard_book.reviews.create(title: "Stole my heart", rating: 5, user: "rene", description: "If you don't love this book, you might not have feelings.")
three_body.reviews.create(title: "Insane!", rating: 5, user: "rene", description: "These books are SO impressive, with such incredible, thought-provoking scope. Highly recommend if you love sci-fi.")
three_body.reviews.create(title: "Too long; didn't read", rating: 3, user: "smitty", description: "I don't read very fast so this book was too hard for me.")
iq84.reviews.create(title: "Fine?", rating: 3, user: "rene", description: "This took me forever to finish, and I'm still not sure whether I actually enjoyed it or not. It's a weird one.")
gone_away.reviews.create(title: "Loved it!", rating: 4, user: "rene", description: "This book is so unique and interesting! Slow start, amazing finish.")
nightingale.reviews.create(title: "Meh", rating: 2, user: "rene", description: "I didn't love this book as much as everyone else did. How much WWII fiction does the world really need.")
goldfinch.reviews.create(title: "Pulitzer, huh?", rating: 1, user: "rene", description: "I thought it was annoying.")
